import Head from "next/head";
import { useEffect } from "react";
import Footer from "../src/sub-components/Footer";
import Navbar from "../src/sub-components/Navbar";
import Ranking from "../src/components/AnimeRankingHome";
import SearchResult from "../src/components/AnimeSearchResult";
import { useStateContext } from "../src/context/StateContext";
import useFunctionsClient from "../src/hooks/useFunctionsClient";

export default function Home() {
  const {
    currentSearchResult,
    setCurrentSearchResult,
    topAiringList,
    setTopAiringList,
    allTimeTopList,
    setAllTimeTopList,
    topMoviesList,
    setTopMoviesList,
    topUpcomingList,
    setTopUpcomingList,
    atHome,
    setAtHome,
    currentQuery,
    setCurrentQuery,
    scroll,
    setScroll,
  } = useStateContext();

  return (
    <>
      <Head>
        <title>WatashiNoAnimeList</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
        setCurrentSearchResult={setCurrentSearchResult}
        currentSearchResult={currentSearchResult}
        currentQuery={currentQuery}
        setCurrentQuery={setCurrentQuery}
        setAtHome={setAtHome}
      />
      {atHome ?
        <Ranking 
          topAiringList={topAiringList}
          setTopAiringList={setTopAiringList}
          allTimeTopList={allTimeTopList}
          setAllTimeTopList={setAllTimeTopList}
          topMoviesList={topMoviesList}
          setTopMoviesList={setTopMoviesList}
          topUpcomingList={topUpcomingList}
          setTopUpcomingList={setTopUpcomingList}
        /> :
        <SearchResult
          currentSearchResult={currentSearchResult}
          setCurrentSearchResult={setCurrentSearchResult}
          currentQuery={currentQuery}
          scroll={scroll}
          setScroll={setScroll}
        />}
      <Footer setCurrentSearchResult={setCurrentSearchResult}
        setCurrentQuery={setCurrentQuery}
        setAtHome={setAtHome} />
    </>
  );
}
